name: START LEDA KANTO

on: [workflow_dispatch]

jobs:
  leda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker compose up --detach --wait
      - name: Run devshell
        uses: addnab/docker-run-action@v3
        with:
            image: ghcr.io/eclipse-leda/leda-distro/leda-devshell:test-0.1.0-m2-part2
            options: --name=leda-devshell --network=leda-network -v ${{ github.workspace }}/kanto:/kanto/ -i --privileged
            run: |
                scp -o StrictHostKeyChecking=no /kanto/sampleapp.json leda-arm64:/data/var/containers/manifests/sampleapp.json
                ssh -o StrictHostKeyChecking=no leda-arm64 'systemctl restart kanto-auto-deployer'
                ssh -o StrictHostKeyChecking=no leda-arm64 'systemctl status kanto-auto-deployer'
                ssh -o StrictHostKeyChecking=no leda-arm64 'sleep 15'
                ssh -o StrictHostKeyChecking=no leda-arm64 'kanto-cm list'
                ssh -o StrictHostKeyChecking=no leda-arm64 'kanto-cm logs sampleapp'


